### ISSUE TITLE
Move test files to src or test folder

### ISSUE THREAD

**Issue by cpaniaguam** [brown-ccv/icesat2-tracks#19]
analysis_db/SA01b_download_tester.py 
analysis/fake_data/A01_1D_spectra.py
analysis/fake_data/S02_spectra_estimates_test.py
analysis/fake_data/S03_spectra_estimates_lomb_scargle.py 
analysis/fake_data/X03_MCMC_surface_smapling.py

**Comment by kmilo9999** [comment]
The file `SA01b_download_tester.py` is actually in the `analysis` folder. Just wondering where did we get this information :confused:

**Comment by cpaniaguam** [comment]
@kmilo9999 See row 149 in https://docs.google.com/spreadsheets/d/1-EVNw4qBYTEq6NfeSzZE-SNHA4e_gQXo/edit#gid=1276144796. Note the value of cell H149 says `Test`. Sorry that it was in the wrong directory! Maybe the contents of the table were computer generated, @hollandjg?

**Comment by kmilo9999** [comment]
We are not using these files in the new pipeline
