### ISSUE TITLE
Rename ICEsat2_SI_tools folder

### ISSUE THREAD

**Issue by kmilo9999** [brown-ccv/icesat2-tracks#30]
This folder has fundamental rutines for the icesat2_tracks pipeline. However, the name can be changed to something more specific to not confuse the user/dev importing these modules.
@mochell Any thoughts ?

**Comment by mochell** [comment]
I think we should simply to with go with: ICESat2Waves 
it carries the Satellite name (ICESat-2) and the meaning, it converts ICESat-2 "2" waves. any obligations?

**Comment by cpaniaguam** [comment]
Seems like a fine package name to me! I personally prefer camel/Pascal case over using dashes. If dashes are used, they will need to be replaced by underscores in a script as we are doing things at the moment. Dashes are not allowed in Python module names.

However, to use it in a script the name should be spelled out using all lowercase letters to adhere to python module naming conventions. According to [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/#:~:text=Modules%20should%20have%20short%2C%20all%2Dlowercase%20names.%20Underscores%20can%20be%20used%20in%20the%20module%20name%20if%20it%20improves%20readability.%20Python%20packages%20should%20also%20have%20short%2C%20all%2Dlowercase%20names%2C%20although%20the%20use%20of%20underscores%20is%20discouraged.), the module name should be `icesat2waves`, which can be a little confusing:
```python
$ pip install ICESat2Waves # care needed for correct spelling
$ python
>>> import icesat2waves # all lowercase 
```

I think renaming it from `icesat2-tracks` to `icesat2waves` and using the latter for PyPi will probably make things easier/simpler. Thoughts?
@mochell @hollandjg @kmilo9999

**Comment by mochell** [comment]
yes lets go with icesat2waves.
