### ISSUE TITLE
Logic vulnerability in B04_angle

### ISSUE THREAD

**Issue by cpaniaguam** [brown-ccv/icesat2-tracks#71]
The variable `LL` is conditionally defined in a try-except block and later used in [L799](https://github.com/brown-ccv/icesat2-tracks/blob/3c176643898634944c1407849b8d1e1cd4f07b5a/src/icesat2_tracks/analysis_db/B04_angle.py#L784) for some plotting routines. What happens if creating `LL` fails?

https://github.com/brown-ccv/icesat2-tracks/blob/3c176643898634944c1407849b8d1e1cd4f07b5a/src/icesat2_tracks/analysis_db/B04_angle.py#L784-L800

I think the rest of the script should also run conditionally. And if `LL` fails to be instantiated, the plotting block starting in L790 should be perhaps  skipped. Thoughts @mochell?

**Comment by mochell** [comment]
@cpaniaguam yes, the plotting in the rest of the file should be conditional. if LL fails we should shoot a warning and not plot. Ideally it should never fail, but that would require to always require the right construction of LL_collect.

**Comment by kmilo9999** [comment]
If there's nothing to plot means the whole processes stop ? or go to the next script ?

**Comment by mochell** [comment]
I think we should go to the next, but everything after this step should know that there is no angle data

**Comment by kmilo9999** [comment]
Resolved by #111
